### ISSUE TITLE
Which IP does it bind to?

### ISSUE THREAD

**Issue by Connoropolous** [holochain/sim2h#6]
When starting up, it would be useful to know which IP it actually bound to, not the 'spec' that it was instructed to bind to, being 0.0.0.0 ... unless I misunderstand how this works.

log output:
`Bound as wss://0.0.0.0:9000/`

**Comment by lucksus** [comment]
Archiving this repo since sim2h got moved over into holochain-rust. Cloned this issue here: https://github.com/holochain/holochain-rust/issues/1803
